import {
  addDecorator,
  configure,
  getStorybookUI,
} from '@storybook/react-native';
import './rn-addons';

// Alternative to require.context not supporter in react-native
// https://github.com/storybooks/storybook/issues/2760
// This file gets auto-generated by react-native-storybook-loader
import { loadStories } from './storyLoader';

configure(loadStories, module);

// Refer to https://github.com/storybooks/storybook/tree/master/app/react-native#start-command-parameters
// To find allowed options for getStorybookUI

export default getStorybookUI;
